server:
  host: "0.0.0.0"
  port: 8080
  basePath: "/devpanel"
  tlsEnabled: false
  tlsCertFile: ""
  tlsKeyFile: ""

auth:
  enabled: true
  secretKey: "change-this-in-production"
  adminUsers:
    - "admin"
  tokenExpiry: 24

projects:
  configPath: "config/projects.yaml"

database:
  type: "postgres"
  path: ""
  host: "195.201.136.53"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbName: "project_website"
  sslMode: "disable" 